### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by a-m-s** [MycroftAI/mimic#59] opened 2016-07-08 08:59 UTC
I see the following test failures.

```
Test project...                 [ FAILED ]
  lex_test_main.c:69: Check strcmp(val_string(val_car(syl)), tok) == 0... failed
  lex_test_main.c:69: Check strcmp(val_string(val_car(syl)), tok) == 0... failed
  lex_test_main.c:69: Check strcmp(val_string(val_car(syl)), tok) == 0... failed
Test atypical...                [ FAILED ]
  lex_test_main.c:69: Check strcmp(val_string(val_car(syl)), tok) == 0... failed

```

Git revision: `0513650`
Configuration: `./configure --prefix=/usr --with-audio=alsa`
Test command: `make -k test`
Host system: `x86_64 Arch Linux`

**Comment by zeehio** [comment] 2016-07-08 09:41
I can't reproduce this on Ubuntu. I will try to find an arch machine to test this.

**Comment by a-m-s** [comment] 2016-07-08 09:57
@zeehio Use the PKGBUILD from the AUR, uncomment the `check` routine, and run `makepkg`

**Comment by zeehio** [comment] 2016-07-15 16:59
I have switched the build system to standard autotools (see #62). Once that is merged all packaging issues should be trivial to solve.

Would you mind please trying this again once #62 is merged?

**Comment by a-m-s** [comment] 2016-07-15 19:33
No problem.

**Comment by zeehio** [comment] 2017-03-20 10:48
Apparently this issue was fixed, since https://aur.archlinux.org/packages/mimic-git/ now provides mimic 1.2.0. I will close this issue, but feel free to reopen if you want to.

Thanks for keeping the AUR package updated! :+1:

**Closed by zeehio** 2017-03-20 10:48 UTC

**Comment by a-m-s** [comment] 2017-03-20 11:13
Sorry, I forgot about this issue. Yes, the testing problems are fixed, and I created a new package for numbered releases. I might move the mimic-git package to the development branch, given that tracking the master branch is pretty pointless for a -git package.
