### ISSUE TITLE
Unable to create audio on Raspberry Pi3

### ISSUE THREAD

**Issue by BongoEADGC6** [MycroftAI/mimic#99] opened 2017-03-06 14:39 UTC
I've tried quite a few times to create voices with Mimic on my rPi3.

I'm able to run `./bin/mimic -t "Hello. Doctor. Name. Continue. Yesterday. Tomorrow." -o hello.wav`
but when i run `aplay hello.wav` I hear no audio, but any other wav file plays just fine.

I installed this with mycroft-core using ./dev_setup.sh

**Comment by BongoEADGC6** [comment] 2017-03-06 15:02
`./bin/mimic -t "Hello. Doctor. Name. Continue. Yesterday. Tomorrow." -o /tmp/hello.wav -v
times faster than real-time: 2.618549
(4.479819 seconds of speech synthesized in 1.710802)`

`aplay /tmp/hello.wav
Playing WAVE '/tmp/hello.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Mono`

**Comment by forslund** [comment] 2017-03-06 16:27
Does sound output work?
`./bin/mimic -t "Hello. Doctor. Name. Continue. Yesterday. Tomorrow."`

Mycroft's configuration should use the alsa backend if I'm not mistaken.

**Comment by zeehio** [comment] 2017-03-06 16:42
In order to find out what is going on, try specifying the voice name as well, just to make sure we are explicit about it:

`./bin/mimic -voice vid_gb_ap -t "Hello. Doctor. Name. Continue. Yesterday. Tomorrow."`

**Comment by forslund** [comment] 2017-03-06 17:28
I think the voice name is shorter, just ap (but I might recall incorrectly):

`./bin/mimic -voice ap -t "Hello. Doctor. Name. Continue. Yesterday. Tomorrow."`

or the path to the voice file

`./bin/mimic -voice  ./voices/mycroft_voice_4.0.flitevox -t "Hello. Doctor. Name. Continue. Yesterday. Tomorrow."`

**Comment by BongoEADGC6** [comment] 2017-03-06 23:02
I get no sound at all. I've even exported it to a windows machine to play through VLC. No luck on that either.

**Comment by BongoEADGC6** [comment] 2017-03-06 23:36
This was after i upgraded to a new version. Everything was working previously.

**Comment by penrods** [comment] 2017-03-07 01:37
What version does Picroft report?   It scrolls by during the bootup, surrounded by =====.  Are you at 0.8.6?

Oh wait, I just read above.  Are you not using a Picroft install?  Just using the dev setup from Github method?

**Comment by BongoEADGC6** [comment] 2017-03-07 01:38
That's correct, Mr. Penrod.

I've since tried to install using the apt package and that worked. So something is broken in the dev_setup.sh from an already existent install.

**Comment by forslund** [comment] 2017-03-07 05:58
@BongoEADGC6 can you verify that you didn't get any sound output from the commands above?

Also can you upload the wav somewhere so I can take a look at it.

also it would be interesting to see if the unittest passes. Try running `make check`.

**Comment by trqx** [comment] 2017-03-07 08:49
Got the same issue after a fresh compilation on a pi 0: slt, rms voices works, ap outputs nothing.
It does work when I use  `-voices "voices/mycroft_voice_4.0.flitevox"` which I believe is "ap".

**Comment by forslund** [comment] 2017-03-07 08:55
Thanks @trqx, yes `ap` is the precompiled version of `voices/mycroft_voice_4.0.flitevox`. That narrows it down somewhat.

**Comment by forslund** [comment] 2017-03-07 12:28
Managed to reproduce and starting to bisect the issue

**Comment by forslund** [comment] 2017-03-07 15:35
Seems to be 3cad70a0a5f6d0e13f882939f15441434ec71fe2 that introduces this behaviour.

**Comment by BongoEADGC6** [comment] 2017-03-07 15:44
@forslund Where would be preferable to upload the audio file?

**Comment by forslund** [comment] 2017-03-07 15:46
@BongoEADGC6 since I've managed to get my rPi up and running there is no need to upload it. I've reproduced the issue and am investigating.

**Comment by zeehio** [comment] 2017-03-07 15:54
Sorry for giving you trouble... I bet there is a const correctness issue. I maybe added a `const` where I should have not and then that const tells the compiler to optimize something.

**Comment by forslund** [comment] 2017-03-07 16:00
@zeehio no need to apologize. The work in cleaning up the build system was huge and one or two bugs are to be expected =)

It's not easy to check all platforms for issues, since this has only cropped up on raspberry Pi it may be some quirk with gcc for that architecture as well.

**Comment by forslund** [comment] 2017-03-08 07:25
@BongoEADGC6, @trqx can any of you try the branch [rpi-ap-voice-fix](https://github.com/MycroftAI/mimic/tree/rpi-voice-ap-fix). To verify that what worked for me actually works for others as well. I still have to figure out the correct way to remove the warnings.

**Comment by trqx** [comment] 2017-03-08 09:20
@forslund 
I guess `git clone https://github.com/MycroftAI/mimic.git -b rpi-voice-ap-fix --depth=1` get only what I need right? Compilation will take a bit of time ony a zero tho.

**Comment by trqx** [comment] 2017-03-08 11:08
@forslund I can confirm, warnings are back and ap voice works with this branch on armv6h.

**Comment by forslund** [comment] 2017-03-08 11:41
Thanks for testing @trqx, tonight I'll re-add the fixes for the warnings one by one and see which one breaks it and how to circumvent it.

**Comment by forslund** [comment] 2017-03-08 18:57
I've pushed an update to the branch and it seems to be working and produces no warnings. I've tested on my Raspberry Pi and on my desktop computer and both seem to work fine.

@BongoEADGC6 or @trqx could one of you verify this before we merge?

**Comment by aatchison** [comment] 2017-03-08 19:12
I'm working on building and testing on my pi.

**Comment by aatchison** [comment] 2017-03-10 17:01
Ok, so I've finally built Mimic twice on the pi. Both the release branch and #100 give me just a pop.
Here is the strace
http://pastebin.com/uXKhHvsu

**Comment by aatchison** [comment] 2017-03-10 17:02
Interestingly enough, I can also not run mimic as sudo.
`root@raspberrypi:/home/pi/mimic# ./mimic -t hello
audio_open_alsa: failed to set hw parameters. Invalid argument.`

**Comment by forslund** [comment] 2017-03-11 00:09
Thanks for testing @aatchison. Did you do a complete build and install? It looks like you are running the system mimic not the locally compiled mimic? I'm guessing you're configuring with `--enable-shared`, is this correct?

I've been running my tests directly from the build directory and doing a basic configuration without any specific flags. I'm building a shared lib version now and will try to install it as well.

As for the root issue, I'm having no issues on vanilla Raspbian.

**Comment by BongoEADGC6** [comment] 2017-03-11 03:14
I tried to clone and build the GitHub repo today. Seems to build cleanly
but still getting static. Guessing I need to reimage my SD to a clean
raspbian image again.

**Comment by forslund** [comment] 2017-03-11 07:34
I did two complete rebuilds of the #100 branch and for my raspberry Pi it's working ok.

No problem what so ever with the statically built mimic.

The one I built with `--enable-shared` and then installing it in the system had some trouble. To run the installed binary I had to help the sysem finding the mimic libraries using
`export LD_LIBRARY_PATH=/usr/local/lib`

If I didn't specifiy the path I got the following error message:
> "mimic: error while loading shared libraries: libttsmimic_lang_all_langs.so.0: cannot open shared object file: No such file or directory"

Looking at @aatchison's strace dump it seem to find the file in the correct place (/usr/local/lib/). Can you try the file before it's installed, running `./mimic` in the build dir?

**Comment by forslund** [comment] 2017-03-11 10:35
For reference this is my procedure:
```sh
git clone https://github.com/MycroftAI/mimic.git -b rpi-voice-ap-fix --depth=1 mimic-rpi
cd mimic-rpi
./autogen.sh
mkdir build
cd build
../configure --enable-shared
make
```
Here I can test the executable before installing:
```sh
./mimic -voice ap -t "Hello there, you are looking well. would you like to see a tree house?"
```
Install on system:
```sh
sudo make install
```

Test system installation

```sh
export LD_LIBRARY_PATH=/usr/local/lib
mimic -voice ap -t "Hello there, you are looking well. would you like to see a tree house?"
```

I have tested this around five times now, Alan Pope speaking loud and clear. Doing the same for master will result in a low buzzing.

@aatchison do you think older mimic installations could be interfering somehow? If they were not uninstalled properly?

**Comment by BongoEADGC6** [comment] 2017-03-11 14:56
@forslund I realized I was trying to clone the main repo, and not your branch. The steps you listed above worked perfectly fine for me.

**Comment by forslund** [comment] 2017-03-11 15:38
@BongoEADGC6 Nice to hear. I'm still trying to figure out why this works and master doesn't but I'll probably push it as a quick fix during the weekend.

**Comment by forslund** [comment] 2017-03-16 22:03
@BongoEADGC6 the branch has been merged, could you verify that master works for you and close this issue if you're happy.

**Comment by BongoEADGC6** [comment] 2017-03-17 13:14
I tried to rebuilt from the mycroft-core and was still unable to.

**Comment by forslund** [comment] 2017-03-17 13:57
I see mycroft core hasn't updated the mimic version number...I'll make a PR to update it tonight

**Comment by zeehio** [comment] 2017-04-18 17:57
I believe this was fixed at https://github.com/MycroftAI/mycroft-core/commit/4a498d97215bcc36d86174279ff0b8324a3b8345 . Am I right?

**Comment by forslund** [comment] 2017-04-18 18:07
Yes, should be fixed. Closing.

**Closed by forslund** 2017-04-18 18:07 UTC
