### ISSUE TITLE
Failing to compile with "cmu_indic_lang.h:54: first defined here"

### ISSUE THREAD

**Issue by matheusfillipe** [MycroftAI/mimic#205] opened 2020-06-01 03:36 UTC
Simply following the instructions for linux at https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mimic-overview, the make command returns:

```
...

  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_f0_trees.lo
  CC       lang/vid_gb_ap/libttsmimic_lang_vid_gb_ap_la-vid_gb_ap_cg_phonestate.lo
  CCLD     libttsmimic_lang_vid_gb_ap.la
  CCLD     libttsmimic_lang_all_voices.la
  CCLD     mimic
/usr/bin/ld: /home/matheus/tmp/mimic/.libs/libttsmimic_lang_cmu_indic_lex.a(cmu_indic_lex.o):/home/matheus/tmp/mimic/lang/cmu_indic_lex/../cmu_indic_lang/cmu_indic_lang.h:54: multiple definition of `cst_rx_not_indic'; ./.libs/libttsmimic_lang_all_langs.a(mimic_lang_list.o):/home/matheus/tmp/mimic/./lang/cmu_indic_lang/cmu_indic_lang.h:54: first defined here
/usr/bin/ld: /home/matheus/tmp/mimic/.libs/libttsmimic_lang_cmu_indic_lang.a(cmu_indic_lang.o):/home/matheus/tmp/mimic/lang/cmu_indic_lang/cmu_indic_lang.h:54: multiple definition of `cst_rx_not_indic'; ./.libs/libttsmimic_lang_all_langs.a(mimic_lang_list.o):/home/matheus/tmp/mimic/./lang/cmu_indic_lang/cmu_indic_lang.h:54: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:3003: mimic] Error 1
make[1]: Leaving directory '/home/matheus/tmp/mimic'
make: *** [Makefile:4805: all-recursive] Error 1

```

I'm running arch linux and gcc 10.1.0.

**Comment by matheusfillipe** [comment] 2020-06-01 03:59
Adding  --disable-lang-indic  to the ./configure command made it work.

**Comment by forslund** [comment] 2020-06-01 11:48
This seems to be a duplicate of #202. I'm closing this issue in favor for the older one. Seems to have something to do with more recent gcc/linkers so I'm going to create an updated dev env and check this out in detail.

**Closed as completed** 2020-06-01 11:48 UTC
